# Generated by Django 3.1.1 on 2020-09-15 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(blank=True, max_length=150, null=True)),
                ('quiz_note', models.CharField(blank=True, max_length=500, null=True)),
                ('quiz_datetime', models.DateTimeField(blank=True, null=True)),
                ('quiz_duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('marks_per_right_answer', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('marks_per_wrong_answer', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quiz_status', models.BooleanField(blank=True, default=False)),
                ('quiz_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
