# Generated by Django 3.1.1 on 2020-10-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200915_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='subject',
        ),
    ]
