# Generated by Django 3.1.1 on 2020-10-28 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20201026_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswers',
            name='studentexam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.studentexam'),
        ),
    ]
