# Generated by Django 3.1.1 on 2020-12-01 11:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_studentanswers_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
