# Generated by Django 3.1.1 on 2020-11-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='all_day',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
