# Generated by Django 3.1.1 on 2020-11-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_auto_20201125_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='duration',
        ),
    ]
