# Generated by Django 3.1.1 on 2020-11-25 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_remove_schedule_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.event'),
            preserve_default=False,
        ),
    ]
