# Generated by Django 3.1.1 on 2020-11-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_auto_20201125_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='title',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='user',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
