# Generated by Django 3.1.1 on 2020-11-25 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_event_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='title',
            new_name='event',
        ),
    ]
