# Generated by Django 3.1.1 on 2020-11-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('subject', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
