"""
Django settings for aws project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
# Import packages
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+2275w^7v%=%&!vu-o=k08475szuma#s#s-+8ll)f5(inr^)$3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'http://djangorocket.com', 'https://djangorocket.com', 'www.djangorocket.com', 'localhost', 'http://djangorocket.com/', 'djangorocket.com' ]


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #CKeditor 
    'ckeditor',
    'ckeditor_uploader',
    #Crispy Forms
    'crispy_forms',
    #Django Countries
    'django_countries',
    #Django-Dash-Plotly
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    # My applications
    'main',
    'todo',
    'quiz',
    'blog',
    'shop',
    'dashreporting',
    'calendar_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'aws.role_middleware.RoleMiddleware', #For role middleware
]

ROOT_URLCONF = 'aws.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],  # Templates pathway
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.cart_context_processors.cart_count'  #Custom context pocessors that can be used header
            ],
        },
    },
]

WSGI_APPLICATION = 'aws.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = { #LOCAL
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'aws', 
        'USER': 'aws_sentez', 
        'PASSWORD': '5482kM392*', 
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = ( os.path.join(BASE_DIR, 'static'), )#Delete for Server

# STATIC_ROOT = os.path.join(BASE_DIR, "static/")   #For SERVER

MEDIA_URL = '/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DATA_UPLOAD_MAX_MEMORY_SIZE = 9242880

#Set same site cookie to none
# SESSION_COOKIE_SECURE                               = True
# SESSION_COOKIE_SAMESITE                             = None

# Email Configuration 
EMAIL_HOST = 'smtp.yandex.com'
EMAIL_HOST_USER = 'info@djangorocket.com'
EMAIL_HOST_PASSWORD = 'Password!'
EMAIL_PORT = '465'
EMAIL_USE_SSL = True

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

####################################
    ##  CKEDITOR CONFIGURATION ##
####################################
 
CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'
 
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = "pillow"
 
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': None,
        'allowedContent': True,
        'width': 'auto',
    },
}
 
###################################

######### CRISPY FORMS ############
CRISPY_TEMPLATE_PACK = 'bootstrap4'

############For Django Plotly Dash ######
X_FRAME_OPTIONS = 'SAMEORIGIN'