# Generated by Django 3.1.1 on 2020-10-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
