# Generated by Django 3.1.1 on 2020-10-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('new', 'new'), ('fre', 'free_shipping')], max_length=20),
        ),
    ]
